import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from "@astrojs/sitemap";
import mdx from "@astrojs/mdx"; 

export default defineConfig({
  site: 'https://enfermerausa.com',
  trailingSlash: 'always',
  build: {
    inlineStylesheets: 'always'
  },
  vite: {
    plugins: [tailwindcss()],
  },
  markdown: {
    drafts: true,
    shikiConfig: {
      theme: "github-dark",
    }
  },
  shikiConfig: {
    wrap: true,
    skipInline: false,
    drafts: true
  },
  integrations: [ sitemap(), mdx()],
  // Old enfermeraenestadosunidos.com paths that now 404 on enfermerausa.com
  redirects: {
    '/blog': '/blog/home/',
    '/blog/': '/blog/home/',
    '/como-homologar-titulo-de-enfermeria-en-estados-unidos': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/como-homologar-titulo-de-enfermeria-en-estados-unidos/': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/guia-completa-para-la-homologacion-de-titulos-de-enfermeria-en-estados-unidos': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/guia-completa-para-la-homologacion-de-titulos-de-enfermeria-en-estados-unidos/': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/guia-honesta-para-la-homologacion-de-enfermeros-en-ee-uu': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/guia-honesta-para-la-homologacion-de-enfermeros-en-ee-uu/': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/enfermeros-a-ee-uu-guia-para-homologar-tu-titulo': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/enfermeros-a-ee-uu-guia-para-homologar-tu-titulo/': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/que-tan-costoso-es-homologar-enfermeria-en-estados-unidos': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/que-tan-costoso-es-homologar-enfermeria-en-estados-unidos/': '/blog/posts/guia-homologacion-titulo-enfermeria-usa-2026/',
    '/validar-tu-titulo-de-enfermeria-en-ee-uu': '/validar-enfermeria-en-usa/',
    '/validar-tu-titulo-de-enfermeria-en-ee-uu/': '/validar-enfermeria-en-usa/',
    '/como-validar-tu-titulo-de-enfermeria-en-u-s-a-paso-a-paso': '/validar-enfermeria-en-usa/',
    '/como-validar-tu-titulo-de-enfermeria-en-u-s-a-paso-a-paso/': '/validar-enfermeria-en-usa/',
    '/como-revalidar-la-carrera-de-enfermeria-en-estados-unidos': '/validar-enfermeria-en-usa/',
    '/como-revalidar-la-carrera-de-enfermeria-en-estados-unidos/': '/validar-enfermeria-en-usa/',
    '/que-es-cgfns': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/que-es-cgfns/': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/cgfns-ahora-es-truemerit-guia-completa-para-enfermeros': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/cgfns-ahora-es-truemerit-guia-completa-para-enfermeros/': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/servicios-de-evaluacion-de-credenciales-ces-para-enfermeria-en-ee-uu-2025': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/servicios-de-evaluacion-de-credenciales-ces-para-enfermeria-en-ee-uu-2025/': '/evaluacion-y-homologacion-de-titulo-enfermeria-usa/',
    '/ofertas-de-trabajo-para-enfermeras-en-ee-uu': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/ofertas-de-trabajo-para-enfermeras-en-ee-uu/': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/como-conseguir-trabajo-como-enfermera-en-estados-unidos': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/como-conseguir-trabajo-como-enfermera-en-estados-unidos/': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/enfermera-en-estados-unidos-como-conseguir-trabajo-2': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/enfermera-en-estados-unidos-como-conseguir-trabajo-2/': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/soy-enfermera-y-quiero-trabajar-en-estados-unidos': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/soy-enfermera-y-quiero-trabajar-en-estados-unidos/': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/que-es-el-nclex-el-examen-de-enfermeria-en-estados-unidos': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/que-es-el-nclex-el-examen-de-enfermeria-en-estados-unidos/': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/como-prepararse-para-el-nclex': '/blog/posts/preparacion-examen-nclex-rn-espanol-2026/',
    '/como-prepararse-para-el-nclex/': '/blog/posts/preparacion-examen-nclex-rn-espanol-2026/',
    '/guia-para-aprobar-el-nclex-a-la-primera': '/blog/posts/estrategias-aprobar-examen-nclex-rn-primer-intento/',
    '/guia-para-aprobar-el-nclex-a-la-primera/': '/blog/posts/estrategias-aprobar-examen-nclex-rn-primer-intento/',
    '/guia-completa-sobre-el-examen-nclex': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/guia-completa-sobre-el-examen-nclex/': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/descifrando-el-nclex': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/descifrando-el-nclex/': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/dominando-el-nclex-guia-completa': '/blog/posts/preparacion-examen-nclex-rn-espanol-2026/',
    '/dominando-el-nclex-guia-completa/': '/blog/posts/preparacion-examen-nclex-rn-espanol-2026/',
    '/cuanto-gana-una-enfermera-en-estados-unidos': '/salarios-de-enfermeros-en-estados-unidos/',
    '/cuanto-gana-una-enfermera-en-estados-unidos/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/tabla-de-salarios-para-enfermeras-registradas-en-estados-unidos-2025': '/salarios-de-enfermeros-en-estados-unidos/',
    '/tabla-de-salarios-para-enfermeras-registradas-en-estados-unidos-2025/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/tabla-salarial-en-enfermeria-en-estados-unidos-una-guia-detallada': '/salarios-de-enfermeros-en-estados-unidos/',
    '/tabla-salarial-en-enfermeria-en-estados-unidos-una-guia-detallada/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/salario-minimo-para-enfermeras-en-los-estados-unidos-en-2025': '/salarios-de-enfermeros-en-estados-unidos/',
    '/salario-minimo-para-enfermeras-en-los-estados-unidos-en-2025/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/trabajos-de-enfermeria-mejor-pagados-en-estados-unidos-para-2025': '/salarios-de-enfermeros-en-estados-unidos/',
    '/trabajos-de-enfermeria-mejor-pagados-en-estados-unidos-para-2025/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/enfermera-en-estados-unidos-cuanto-te-pagan': '/salarios-de-enfermeros-en-estados-unidos/',
    '/enfermera-en-estados-unidos-cuanto-te-pagan/': '/salarios-de-enfermeros-en-estados-unidos/',
    '/visa-h1b-para-enfermeros-en-ee-uu-guia-completa': '/proceso-de-visa-y-relocalizacion-para-enfermeras/',
    '/visa-h1b-para-enfermeros-en-ee-uu-guia-completa/': '/proceso-de-visa-y-relocalizacion-para-enfermeras/',
    '/visas-para-enfermeros-a-usa-tn-h1b-eb3': '/proceso-de-visa-y-relocalizacion-para-enfermeras/',
    '/visas-para-enfermeros-a-usa-tn-h1b-eb3/': '/proceso-de-visa-y-relocalizacion-para-enfermeras/',
    '/residencia-permanente-para-enfermeras-en-ee-uu-en-2025': '/blog/posts/visa-eb3-enfermeras-green-card-hospitales-usa/',
    '/residencia-permanente-para-enfermeras-en-ee-uu-en-2025/': '/blog/posts/visa-eb3-enfermeras-green-card-hospitales-usa/',
    '/patrocinio-de-enfermeras-en-ee-uu-para-2025': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/patrocinio-de-enfermeras-en-ee-uu-para-2025/': '/ofertas-de-empleo-para-enfermeras-en-usa/',
    '/requisitos-del-pte-academic-para-la-licencia-de-enfermeria-registrada-en-los-estados-de-ee-uu': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/requisitos-del-pte-academic-para-la-licencia-de-enfermeria-registrada-en-los-estados-de-ee-uu/': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/requisitos-del-pte-para-enfermeria-en-ee-uu-para-2025': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/requisitos-del-pte-para-enfermeria-en-ee-uu-para-2025/': '/licencia-de-enfermeria-y-examen-nclex-usa/',
    '/un-dia-en-la-vida-la-rutina-de-una-enfermera-registrada-en-los-ee-uu-para-2025': '/blog/posts/como-es-un-dia-como-enfermera-en-usa-rutinas-turnos/',
    '/un-dia-en-la-vida-la-rutina-de-una-enfermera-registrada-en-los-ee-uu-para-2025/': '/blog/posts/como-es-un-dia-como-enfermera-en-usa-rutinas-turnos/',
  }
});